backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "originals"
    label: "Original Paintings"
    folder: "content/originals"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "prints"
    label: "Prints"
    folder: "content/prints"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "commissions"
    label: "Commissions & Murals"
    folder: "content/commissions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Name", name: "client", widget: "string" }
      - { label: "Project Details", name: "details", widget: "markdown" }
      - { label: "Reference Image", name: "image", widget: "image", required: false }
